### ISSUE TITLE
issue with diamond spawn

### ISSUE THREAD

**Issue by grateremo** [Kasax007/Dreamcraft-Development-#1]
I played around in a creative world for a bit with quarries to find that diamonds have to be one of the hardest things to find doing a 4x4 chunk and not finding a single diamond and looking at the world ore gen seeing that it's around 0.001% or lower.

Either that can be fixed in a config file that i can't find, or maybe look at adding MMD OreSpawn if you can.

**Comment by Kasax007** [comment]
Thanks for pointing that out. I did also notice that when playtesting. My guess is, that this is because of all the other ores added to the world generation. Luckily there are many other ways for you to get more than enough diamonds :) Most of the dungeons give you a considerable amount of them and there are also two ore crop mods for the player to use to get renewable diamonds. The easiest way to get diamonds while mining still will probably be exploring big caves manually and not using a quarry. 

Also, another current issue with the quarries is that they currently don't all mine below y=0. And the most diamonds spawn below that y level now. Depending on the quarry you used that will also have affected the outcome. 

I would appreciate some feedback on the mod pack in general if you have any suggestions of things to change or if you like it so far :D 
Thanks for playing tho!

**Comment by Kasax007** [comment]
Sadly there is no config file, which can change the number of diamonds generated, and MMD OreSpawn is not yet updated for 1.17.X.
Maybe I can find a fix for this in the future but for now, I am afraid I can't change anything about it.

**Comment by Kasax007** [comment]
I did some more testing and the ore generation looks somewhat like this for me https://imgur.com/Fh848Jm .
So I really don't have an issue finding a lot of diamonds. Yes, you have to mine low to find more. Higher up at like y = 0 there are very little diamonds but below that there are more. 

If you want to test this for yourself you can grab yourself a command block set it to always active and repeating and put this command in it: execute as @a at @a run fill ~-20 ~-8 ~-20 ~20 ~8 ~20 air replace minecraft:deepslate

Then just fly around in the deepslate area.
